

* Chapter 1 线性代数概要与提高

** 满秩分解 (Non-uniqueness)
   (*rank decomposition* or *rank factorization*)

定义: 设 $A\ne{0 }$ , 如果列满秩矩阵 $L$ 与行满秩矩阵 $R$ 使得 $A=LR$ , 则称 $A=LR$
      是 $A$ 的一个满秩分解. (P9)

求解: 首先化为 Hermite 标准型 , 再取对应的列构成 $L$      
      #+BEGIN_SRC matlab
      L = orth(A)
      R = L'*A
      #+END_SRC

** 酉矩阵

   设 $\alpha_1,\alpha_2,\ldots,\alpha_n$ 是 $V=R^n$ 或 $V=C^n$ 的一组标准正交基,则矩阵
   $Q=(\alpha_1,\alpha_2,\ldots,\alpha_n)$ 称为酉矩阵
   1) 矩阵 $Q$ 是酉矩阵 $\Longleftrightarrow{Q^*Q=I}$
   2) 实的酉矩阵称为正交矩阵.

** Hermite矩阵

定义: 复共轭对称矩阵: $A^*=A$

定理: Hermite矩阵的特征值均为实数,且属于不同特征值的特征向量彼此正交.

定理: Hermite矩阵 $A$ 可以酉对角化,即存在酉矩阵 $U$ 使得 $U^*AU=D$ 是对角矩阵.特别的,
      实对称矩阵可以正交对角化.

** Hermite二次型

定义: $f(x)=x^*Ax=\sum_{i=1}^n\sum_{j=1}^nb_{ij}\overline{x}_ix_j$ ,矩阵 $A$ 称为
      二次型 $f(x)$ 的矩阵.

定义: 设 $f(x)=x^*Ax$ 是复二次型, $A$ 是Hermite矩阵,若对任意非零向量 $\alpha\in{C^n}$,
      均有 $f(\alpha)=\alpha^*A\alpha>0$ ,则称 $f(x)$ 是正定二次型, $A$ 是正定矩阵.

** Hermite矩阵定理

   设 $A$ 是 $n$ 阶Hermite矩阵,则下列条件等价
   1) $A$ 是正定的
   2) $f(x)=x^*Ax$ 是正定二次型
   3) $A$ 的特征值均为正实数
   4) 存在 $m\times{n}$ 阶列满秩矩阵 $M$ ,使得 $A=M^*M$
   5) 存在 $n$ 阶可逆矩阵 $M$ ,使得 $A=M^*M$
   6) 存在 $n$ 阶可逆矩阵 $P$ ,使得 $P^*AP=I$ (即 $A$ 与 $I$ 合同)

** 正定矩阵与内积的关系

   - 设 $\alpha_1,\alpha_2,\ldots,\alpha_n$ 是 $n$ 维内积空间 $V$ 的一组基,设 $\alpha,\beta\in{V}$ 的
     坐标分别是 $x=(x_1,x_2,\ldots,x_n)^T,y=(y_1,y_2,\ldots,y_n)^T$ ,
     则有 

     $(\alpha,\beta)=(\sum_{i=1}^nx_i\alpha_i,\sum_{j=1}^ny_j\alpha_j)=\sum_{i=1}^n\sum_{j=1}^n(\alpha_i,\alpha_j)x_i\overline{y}_j$

     记 $(\alpha_i,\alpha_j)=a_{ji}$ ,则公式变为 
                               $$(\alpha,\beta)=y^*Ax$$
     $A=(a_{ij})$ 是 Hermite 矩阵,由内积的正定性知 $A$ 是正定矩阵
     $A$ 称为基 $\alpha_1,\alpha_2,\ldots,\alpha_n$ 的 度量矩阵 或 Gram 矩阵.

定理: 设 $V$ 是 $n$ 维复线性空间,则其上的内积与正定矩阵一一对应.
      1) 标准正交基的度量矩阵是单位矩阵

** 双线性型

   - 对任意 $n$ 阶复矩阵 $A=(a_{ij})$ ,称
     $y^*Ax=\sum_{i=1}^n\sum_{j=1}^na_{ji}x_i\overline{y}_j$
     为矩阵 $A$ 的双线性型或 $C^n$ 上的双线性型.
   
* Chapter 2 矩阵与线性变换

** 子空间:直和与空间分解

*** 子空间

定义： 设 $V$ 是一个线性空间， $U$ 是 $V$ 的一个非空子集。如果 $U$ 本身关于 $V$ 的向量
      加法和数乘作成一个线性空间，则称 $U$ 是 $V$ 的一个子空间。

*** 直和

    1. $U+W$ 是子空间，且是包含 $U$ 与 $W$ 的最小的子空间，称为 $U$ 与 $W$ 的和.

    2. 如果 $U\cap{W}=0$ , 此时我们称 $U+W$ 是 *直和*, 记为 $U\oplus{W}$,
       	因此 $dim(U\oplus{W})=dimU+dimW$.

***  补子空间

     1. 设 $V$ 是线性空间, $U$ 是 $V$ 的一个子空间, 则存在另一个子空间 $W$, 使得 $V=U\oplus{W}$.
       	$W$ 称为 $U$ 的补子空间. $U$ 的补子空间一般不是唯一的.

** 矩阵与线性变换

** 内积空间的正交分解

*** 内积空间

定义: 设 $F$ 是实数域或复数域, $V$ 是 $F$ 上的线性空间. 若对 $V$ 中任意两个向量 $\alpha,\beta$ ,都定义了
      $F$ 中一个数 $(\alpha,\beta)$ (称为向量 $\alpha$ 与 $\beta$ 的内积), 使得
      1) (共轭对称性) $(\alpha,\beta)=\overline{(\beta,\alpha)}$ ,其中 $\overline{(\beta,\alpha)}$ 是复数 $(\beta,\alpha)$ 的共轭复数;
      2) (正定性) $(\alpha,\alpha)\ge0$ ,且等号成立 $\Longleftrightarrow\alpha=0$ ;
      3) (双线性) $(a\alpha+b\beta,\gamma)=a(\alpha,\gamma)+b(\beta,\gamma)$ ,对任意 
	 $\alpha,\beta,\gamma\in{V},\ a,b\in{F}$ 成立.

*** 欧式空间,酉空间

    1. 欧式空间: 有限维实内积空间
    2. 酉空间: 复内积空间( $F=C$ )

*** 正交补
定义: 设 $V$ 是 $n$ 维内积空间, $U$ 是 $V$ 的子空间. 令 $W=\{\alpha\in{V}|(\alpha,\beta)=0,\forall{\beta}\in{U}\}$ .
      $W$ 是 $V$ 的一个子空间,称为 $U$ 的正交补,记为 $U^{\bot}$ .

*** 最佳近似定理

    设 $U$ 是欧式空间 $V$ 的子空间, $\beta\in{V},\alpha\in{U}$ ,则 $\alpha$ 是 $\beta$ 在 $U$ 上的最佳近似向量
    $\Longleftrightarrow\beta-\alpha\in{U^{\bot}}$ .

** 内积空间中的线性变换

*** 等距变换   

定义: 设 $V$ 是内积空间, $\sigma\in{End\ V}$ .如果 $\sigma$ 保持向量间的距离,即对任意 $\alpha,\beta\in{V}$ ,均有
      $d(\sigma(\alpha),\sigma(\beta))=d(\alpha,\beta)$ ,则称 $\sigma$ 是等距变换或保距变换.

定理: 设 $V$ 是内积空间, $\sigma\in{End\ V}$ ,则 $\sigma$ 是等距变换 $\Longleftrightarrow\sigma$ 保持向量的长度
      $\Longleftrightarrow\sigma$ 保持内积( $(\sigma(\alpha),\sigma(\beta))=(\alpha,\beta)$ ).

定理: 设 $V$ 是 $n$ 维内积空间, $\alpha_1,\alpha_2,\ldots,\alpha_n$ 是 $V$ 的一组标准正交基, $\sigma\in{End\ V}$ ,
      $A$ 是 $\sigma$ 在该组基下的矩阵,则 $\sigma$ 是等距变换 $\Longleftrightarrow$ $A$ 是酉矩阵( $A^*A=I$ ).
      注意: 条件必须是标准正交基

      1) 欧式空间的等距变换称为正交变换
      2) 复内积空间的等距变换称为酉变换
	 
定理: 设 $V$ 是内积空间, $\sigma\in{End\ V}$ ,则 $\sigma$ 是等距变换 $\Longleftrightarrow$ $\sigma$ 将标准正交基变为标准正交基.	

*** Givens 变换

    1. 定义[p63]

       由矩阵 
       
       \begin{eqnarray}\begin{bmatrix}c&s\\-s&c \end{bmatrix} \end{eqnarray}
       
       决定的旋转称为 Jacobi 旋转或 Givens 旋转.一般地,设 $c^2+s^2=1,\theta=arctan\frac{s}{c}$ ,则将 $n$ 阶实矩阵
       
       $G(i,j,\theta)=I_n-(1-c)(E_{ii}+E_{jj})+s(E_{ij}-E_{ji})$
       
       称为 Givens 旋转矩阵.这是一个正交矩阵.

*** 对称变换(自伴变换)

定义: 设 $\sigma$ 是欧式空间 $V$ 的线性变换.如果对任意 $\alpha,\beta\in{V}$ ,均有 $(\sigma(\alpha),\beta)=(\alpha,\sigma(\beta))$ ,
      则称 $\sigma$ 是一个对称变换.
      
定理: 欧式空间的线性变换 $\sigma$ 是对称变换 $\Longleftrightarrow\ \sigma$ 在一组标准正交基下的矩阵是对称矩阵.

*** 伴随变换[p64]
    
* Chapter 3 特征值与矩阵的Jordan标准型

** Schur 三角化定理: 化简矩阵的基础
   
*** Schur(酉)三角化定理

定理: 设 $A\in{C^{n\times{n}}}$ ,则存在酉矩阵 $U$ ,使
      $U^*AU=B$ ,其中, $B$ 为一个上三角矩阵.

      注意: 实矩阵不成立

*** 分块 Schur 三角化定理

引理: 设 $A=(a_{ij})$ 是 $F$ 上的任意上三角矩阵, $1\le{}p<q\le{}n$ ,设
      $P=I+\alpha{}E_{pq},\alpha\in{F}$ ,则 $B=(b_{ij})=P^{-1}AP$ 是与 $A$
      的主对角线相同(包括顺序)的上三角矩阵,且 $b_{pq}=a_{pq}+\alpha(a_{pp}-a_{qq})$ .
      特别地,若 $a_{pp}\ne{a_{qq}}$ ,则可选取适当的 $\alpha$ ,使得 $b_{pq}=0$.

      注意: $F$ 不必是复数域

定理(p90): (分块Schur三角化定理) 设 $n$ 阶复矩阵 $A$ 的特征多项式 $|\lambda{}I-A|=\prod_{i=1}^{s}(\lambda-\lambda_i)^{n_i}$ ,
           其中, $\sigma(A)=\{\lambda_i:1\le{i}\le{s}\},\sum_{i=1}^{s}n_i=n$ ,则存在可逆矩阵 $P$,使得

	   $P^{-1}AP=A_1\oplus{A_2}\oplus{}\ldots\oplus{A_s}$

	   其中 $A_i$ 是特征值均为 $\lambda_i$ 的 $n_i$ 阶上三角矩阵.

*** Cayley-Hamilton 定理

    - 设 $A$ 是 $n$ 阶严格上三角矩阵,则 $A^n=0$ .
      
    - 定理(p90): 
      设矩阵 $A$ 的特征多项式为 $f(\lambda)$ ,则有 $f(A)=0$ .

      * $A$ 的特征多项式为

	$f(\lambda)=(\lambda-\lambda_1)^{n_1}(\lambda-\lambda_2)^{n_2}\cdots(\lambda-\lambda_s)^{n_s}$
	 
	$f(A)=(A-\lambda_1I)^{n_1}(A-\lambda_2I)^{n_2}\cdots(A-\lambda_sI)^{n_s}$

    - 由于 $n$ 阶矩阵 $A$ 的特征多项式是 $n$ 次多项式, Cayley-Hamilton 定理表明, $A$ 的 $n$ 次幂
      可由其较低次幂的线性组合给出.即 $n$ 阶矩阵 $A$ 的任意次幂均属于由 $I,A,A^2,\cdots,A^{n-1}$
      生成的 $M_n(C)$ 的子空间.

      对任意自然数 $m$:
      
      $A^m\in{}span\{I,A,A^2,\cdots,A^{n-1}\}$

*** Sylvester 降幂公式

    1. 命题[p91]
       设 $A$ 与 $B$ 分别是 $m\times{n}$ 与 $n\times{m}$ 矩阵, $m\ge{n}$ ,
       则

       $\mid{}\lambda{}I_m-AB\mid{}=\lambda^{m-n}\mid{}\lambda{}I_n-BA\mid{}$

*** 零化多项式,最小多项式

    1. 定义[p92]
       设 $A$ 是 $n$ 阶矩阵, $f(x)$ 是多项式,如果 $f(A)=0$ ,则称 $f(x)$ 是 $A$ 的
       零化多项式,次数最低的首一零化多项式称为 $A$ 的最小多项式,记为 $m_A(x)$ 或 $m(x)$ .

    2. 命题[p92]
       设 $m(x)$ 是 $A$ 的最小多项式, $f(x)$ 是 $A$ 的任意零化多项式,则 $m(x)\mid{}f(x)$ .特别地,
       $m(x)\mid\ \mid{}xI-A\mid$ .

    3. 命题[p94]
       设 $A$ 是任意方阵, $m(x)$ 是 $A$ 的最小多项式,设 $\lambda_0\in{C}$ ,则 $\lambda_0$ 是 $A$ 的
       特征值 $\Longleftrightarrow{}m(\lambda_0)=0$ .

    4. 命题[p94]
       矩阵 $A$ 是幂零矩阵 $\Longleftrightarrow{A}$ 的特征值均为0.

    5. 命题[p94]
       分块对角矩阵的最小多项式等于各个子块的最小多项式的最小公倍式.
       分块对角矩阵的特征多项式等于各个子块的特征多项式的乘积.

    6. 命题[p94]
       相似矩阵具有相同的最小多项式.

    7. 命题[p94]
       矩阵 $A$ 可以对角化 $\Longleftrightarrow{A}$ 的最小多项式没有重根.

    8. 推论[p95]
       设 $A$ 为方阵, $f(x)$ 是无重因式的多项式.若 $f(A)=0$ ,则 $A$ 可以对角化.
       
       * 幂等矩阵( $A^2=A$ )与对合矩阵( $A^2=I$ )均可以对角化(最小多项式无重根).

*** 线性变换的特征值与特征向量

    1. 设 $V$ 是 $C$ 上的线性空间(可以是无限维), $\sigma\in{}End\ V,\lambda\in{C}$ .如果存在
       非零向量 $\alpha\in{V}$ 使得 $\sigma(\alpha)=\lambda{\alpha}$ ,则称 $\lambda$ 是 $\sigma$ 的一个特征值,而 $\alpha$ 是
       $\sigma$ 的一个特征向量.

    2. 定理[p95]
       设 $V$ 是有限维线性空间, $\sigma\in{End\ V},A$ 是 $\sigma$ 在某组基下的矩阵,则
       1) $A$ 与 $\sigma$ 有完全相同的特征值(即重数也一样)

       2) 设 $\sigma$ 的不同特征值为 $\lambda_1,\cdots,\lambda_s$ ,则 $A$ 可以对角化 $\Longleftrightarrow{}V=\sum_{i=1}^{s}\oplus{V_{\lambda_i}}$ .
	  于是 $A$ 可以对角化 $\Longleftrightarrow{}\sigma$ 可以对角化,即 $\sigma=\sum_{i=1}^s\oplus\sigma_i$ ,其中, $\sigma_i$ 是 $\sigma$ 在
	  $V_{\lambda_i}$ 上的限制.

** Jordan 标准形：复数矩阵的一种最简形式

   - 分块 Schur 三角化定理将寻求矩阵标准形的问题转化为寻找主对角线元素均相同的上三角矩阵
     的标准形。这样的矩阵可以写成
     
     $A=\lambda{}I+N$
     
     的形式,其中 $N$ 是严格上三角矩阵.因为
     
     $P^{-1}AP=\lambda{}I+P^{-1}NP$
     
     故只需研究严格上三角矩阵的标准形即可.

   - 设 $A$ 是 $n$ 阶严格上三角矩阵且 $r(A)=n-1$ ,则 $A$ 与 $J_n$ 相似

   - 设 
     \begin{equation}
     A=
     \begin{bmatrix}
     0&J_3\\0&0^T
     \end{bmatrix}
     \end{equation}
     
     是 $4$ 阶严格上三角矩阵,注意 $A$ 不与 
     
     \begin{equation}
     B=
     \begin{bmatrix}
     J_3&0\\0^T&0
     \end{bmatrix}
     \end{equation}
     
     相似,而与 $C=J_2\oplus{}J_2$ 相似.

*** 严格上三角矩阵的标准形

    - 对 $2\le{}r(A)\le{}n-2$ 的 $n$ 阶严格上三角矩阵 $A$ 来说,其标准形并不能由其秩完全
      确定.

    - 严格上三角矩阵的幂零指数对其标准形有重要意义

*** 幂零矩阵的一些性质

    - 命题[p97]
      
      1) $J_n^TJ_n=(0)\oplus{}I_{n-1}$
	 $J_nJ_n^T=I_{n-1}\oplus{}(0)$

      2) $J_ne_i=e_{i-1}$ ,其中 $e_i$ 是标准向量,约定 $e_0$ 是 $0$ 向量

      3) 对任意 $x\in{C^n},(I_n-J_n^TJ_n)x=(x^Te_1)e_1$

*** 幂零矩阵的 Jordan 标准形定理

    - 定理[p97]

      设 $A$ 是 $n$ 阶严格上三角复矩阵,则存在可逆矩阵 $P$ 和正整数 $n_1\ge{}n_2\ge{}\cdots\ge{}n_m$,
      $n_1+n_2+\cdots+n_m=n$ ,使得
      
      $P^{-1}AP=J_{n_1}\oplus{}J_{n_2}\oplus{}\cdots\oplus{}J_{n_m}$
      
      上式右端的矩阵称为幂零 Jordan 矩阵,它是矩阵 $A$ 的 Jordan 标准形,一般记为 $J$.如果不计诸 $n_j$ 的次序和
      大小,则 $A$ 的 Jordan 标准形是唯一的.

    - 推论[p99]

      设 $M$ 与 $N$ 是两个 $n$ 阶幂零矩阵,
      
      则 $M$ 与 $N$ 相似 $\Longleftrightarrow{}r(M^k)=r(N^k),\forall{k\ge{1}}$

*** Jordan 标准形定理

    1. 定义
      
       矩阵 $\lambda{}I_n+J_n$ 称为 $n$ 阶 $\lambda-Jordan$ 块,记为 $J_n(\lambda)$

    2. 定理 (Jordan 标准形定理)[p99]
      
       设 $A$ 是 $n$ 阶复矩阵,则存在可逆矩阵 $P$ 和正整数 $n_1\ge{}n_2\ge{}\cdots\ge{}n_m$ ,
       $n_1+n_2+\cdots+n_m=n$ ,使得
      
       $P^{-1}AP=J_{n_1}(\lambda_1)\oplus{}J_{n_2}(\lambda_2)\oplus\cdots\oplus{}J_{n_m}(\lambda_m)$
      
       上式右端的矩阵称为 Jordan 矩阵,它是矩阵 $A$ 的 Jordan 标准形.如果不计诸 $n_j$ 的次序与大小,
       则 $A$ 的 Jordan 标准形是唯一的.

    3. 推论
      
       方阵 $A$ 可以对角化 $\Longleftrightarrow{}A$ 的 Jordan 标准形是对角矩阵

    4. 意义
      
       一个矩阵的 Jordan 标准形不仅具有非常简单的形式,而且包含了该矩阵的几乎所有信息,比如 
       秩,特征值,线性无关的特征向量的个数,特征子空间的维数等.

*** 幂零矩阵的 Jordan 标准形的最大块的阶数

    - 命题[p100] (最大 Jordan 块)
      
      设 $A$ 是严格上三角矩阵,则其 Jordan 标准形的 Jordan 块的阶数的最大值等于其幂零指数.

*** Jordan 标准形的计算 (严格上三角矩阵)

    - 对阶数较小的幂零矩阵可以通过其幂零指数和秩来确定其 Jordan 标准形

    - 定理[p100]
      
      设 $n$ 阶严格上三角矩阵 $A$ 的 Jordan 标准形 $J$ ,其幂零指数为 $e$ ,则
      
      1) $e=\max{\{n_i:1\le{i}\le{m}\}}$

      2) $J$ 中 Jordan 块的个数 $m$ 等于 $A$ 的零度

      3) 记 $J$ 中 $k$ 阶 Jordan 块的个数为 $l_k$ , $A^k$ 的零度为 $\eta_k$, $0\le{k}\le{m}$ .则
	 
	 $l_k=2\eta_k-\eta_{k-1}-\eta_{k+1},1\le{k}\le{m}$
	
*** Jordan 标准形的计算 (一般矩阵)

    - 设 $n$ 阶矩阵 $A$ 的 Jordan 标准形 $J$ 同 [[Jordan 标准形定理]] .设 $\mu$ 为
      $A$ 的一个特征值,记 $(A-\mu{I})^k$ 的零度为 $\eta_k$ , $J$ 中对角线元素
      为 $\mu$ 的 $k$ 阶 Jordan 块的个数为 $l_k$ ,则
      
      1) $\eta_1$ 等于 $J$ 中对角线元素为 $\mu$ 的 Jordan 块的个数

      2) $l_1=2\eta_1-\eta_2,l_2=2\eta_k-\eta_{k-1}-\eta_{k+1},k\ge{2}$
	 



* Chapter 4 正规矩阵与矩阵分解

** 正规矩阵

*** 酉对角化判定定理

    - 定理[p122] 可以酉对角化的"好矩阵"的一个直接的判断

      矩阵 $A$ 可以酉对角化 $\Longleftrightarrow{}AA^*=A^*A$

*** 正规矩阵定义

    1. 定义[p123]
       设 $A\in{}C^{n\times{n}}$, 若 $AA^*=A^*A$ ,则称 $A$ 为正规矩阵.

    2. 实对称矩阵,实反对称矩阵,酉矩阵,正交矩阵,Hermite矩阵,反Hermite矩阵都是正规矩阵.

    3. 引理[p123]
       设 $A$ 为正规矩阵,若 $A$ 又为三角矩阵,则 $A$ 为对角矩阵.

    4. 将正规矩阵 $A$ 酉对角化的酉矩阵的每一列都是 $A$ 的特征向量.

    5. 定理[p123]
       设 $A\in{}C^{n\times{n}}$ ,则 $A$ 为正规矩阵 $\Longleftrightarrow{A}$ 有 $n$ 个两两正交的单位
       特征向量.

    6. 推论[p123]
       正规矩阵属于不同特征值的特征向量是相互正交的.

    7. 定理[p123]
       设 $A=(a_{ij})_{n\times{n}}$ 是复矩阵, $\lambda_1,\lambda_2,\cdots,\lambda_n$ 为 $A$ 的
       $n$ 个特征值,则
      
       1) (Schur 不等式) $\sum_{i=1}^{n}\mid{\lambda_i}\mid^2\le\sum_{i,j=1}^n\mid{a_{ij}}\mid^2$

       2) $A$ 为正规矩阵 $\Longleftrightarrow\sum_{i=1}^{n}\mid\lambda_i\mid^2=\sum_{i,j=1}^{n}\mid{a_{ij}}\mid^2$

    8. 若 $A$ 是正规矩阵,则与 $A$ 酉相似的矩阵仍为正规矩阵.

*** Schur 型
    - 设 $a$ 与 $b$ 是实数且 $b\ne{0}$ ,则称二阶实矩阵
      
      \begin{equation}
      \begin{bmatrix}
      a&b\\-b&a
      \end{bmatrix}
      \end{equation}
      
      为一个 Schur 型. Schur 型正是复数 $a+bi$ 的矩阵表示,一个 Schur 型的特征值正是复数 $a\pm{bi}$ .

    - 每个 Schur 型都是正规矩阵,酉相似与对角矩阵 $(a+bi)\oplus(a-bi)$ ,但不能正交对角化.

*** 实正规矩阵在正交变换下的最简形式
**** 定理[p124] 实正规矩阵
      设 $A$ 是 $n$ 阶实矩阵,则 $A$ 是正规矩阵 $\Longleftrightarrow$ 存在正交矩阵 $Q$ 使得
      
      $Q^TAQ=A_1\oplus{A_2}\oplus\cdots\oplus{A_s}$
      
      其中每个 $A_i$ 或者是一阶实矩阵,或者是一个 Schur 型.

**** 推论[p124] 
      设 $A$ 是 $n$ 阶实矩阵
      
      1) $A$ 是对称矩阵 $\Longleftrightarrow$ 存在正交矩阵 $Q$ ,使得 $Q^TAQ$ 是对角矩阵

      2) $A$ 是反对称矩阵 $\Longleftrightarrow$ 存在正交矩阵 $Q$ ,使得
	 
	 $Q^TAQ=0\oplus{A_1}\oplus{A_2}\oplus\cdots\oplus{A_s}$
	 
	 其中每个 
	 
	 \begin{equation}A_i=\begin{bmatrix}0&b_i\\-b_i&0\end{bmatrix}\end{equation}
	 
	 从而反对称矩阵的非零特征值为纯虚数.

      3) $A$ 是正交矩阵 $\Longleftrightarrow$ 存在正交矩阵 $Q$ ,使得
	 
	 $Q^TAQ=I_s\oplus(-I_t)\oplus{A_1}\oplus{A_2}\oplus\cdots\oplus{A_m}$
	 
	 其中每个 $A_i$ 是二阶 Givens 旋转矩阵,从而正交矩阵的特征值的模均为 $1$ .
	 
	 设 $B$ 是 $n$ 阶复矩阵

      4) $B$ 是 Hermite 矩阵 $\Longleftrightarrow$ 存在酉矩阵 $U$ ,使得 $U^*BU$ 是实对角矩阵.

      5) $B$ 是 反Hermite 矩阵 $\Longleftrightarrow$ 存在酉矩阵 $U$ ,使得 $U^*BU$ 是纯虚数对角矩阵(即实部为0)

      6) $B$ 是酉矩阵 $\Longleftrightarrow$ 存在酉矩阵 $U$ ,使得 $U^*BU$ 是对角元素的模均为1的对角矩阵,从而
	 酉矩阵的特征值的模均为1.

      7) Hermite 矩阵 $A$ 正定 $\Longleftrightarrow$ $A$ 的所有顺序主子式均大于0.

**** 引理[p125]
   Hermite 阵或实对称矩阵 $A$ 在某一个 $k$ 维子空间上正定 $\Longleftrightarrow{A}$ 至少有 $k$ 个特征值(包括重数)大于零.

*** Hermite 矩阵与二次型
    设 $A$ 为 $n$ 阶 Hermite 矩阵, $x^*Ax$ 是相应的复二次型,则 $A$ 可以酉对角化等价于该复二次型可以通过
    酉变换(即等距变换)化为

    $\lambda_1\mid{y_1}\mid^2+\lambda_2\mid{y_2}\mid^2+\cdots+\lambda_n\mid{y_n}\mid^2$

    由于特征值 $\lambda_i$ 均为实数,所以 $Hermite$ 矩阵对应的复二次型的值总是实数.若 $A$ 还是可逆矩阵,则
    诸特征值均非零,它们的倒数正是主轴平方.

** 正规矩阵的谱分解

*** 定义
    - 设 $A$ 为正规矩阵,则由[[酉对角化判定定理]]知,存在酉矩阵 $U$ 使得 $U^*AU=diag(\lambda_1,\lambda_2,\cdots,\lambda_n)$ .
      因而 $A=Udiag(\lambda_1,\cdots,\lambda_n)U^*$ .令 $U=(\alpha_1,\alpha_2,\cdots,\alpha_n)$ ,则
    
      \begin{eqnarray}A=(\alpha_1,\alpha_2,\cdots,\alpha_n)
      \begin{bmatrix}
      \lambda_1&&&\\&\lambda_2&&\\&&\ddots&\\&&&\lambda_n
      \end{bmatrix}
      \begin{bmatrix}
      \alpha_1^*\\\alpha_2^*\\\vdots\\\alpha_n^*
      \end{bmatrix}\nonumber\\
      =\lambda_1\alpha_1\alpha_1^*+\lambda_2\alpha_2\alpha_2^*+\cdots+\lambda_n\alpha_n\alpha_n^*
      \end{eqnarray}
    
      由于 $\lambda_1,\lambda_2,\cdots,\lambda_n$ 为 $A$ 的特征值, $\alpha_1,\alpha_2,\cdots,\alpha_n$ 为对应的两两正交的单位特征向量,故
      上式称为正规矩阵 $A$ 的谱分解或特征(值)分解.
 
    - 若把公式中系数相同的放在一起(0特征值对应的项去掉),然后把系数提出来,则公式就变成了

      $A=\lambda_1P_1+\lambda_2P_2+\cdots+\lambda_sP_s$

      其中 $\lambda_1,\lambda_2,\cdots,\lambda_s$ 为 $A$ 的互不相同的非零特征值. 由于
      
      $(\alpha_i\alpha_i^*)^*=\alpha_i\alpha_i^*,1\le{i}\le{n}$
      
      $(\alpha_i\alpha_i^*)(\alpha_j\alpha_j^*)=0,1\le{i}\ne{j}\le{n}$
      
      $(\alpha_i\alpha_i^*)^2=\alpha_i\alpha_i^*,1\le{i}\le{n}$

      从第二章幂等矩阵与投影变换的对应关系可知, $P_i$ 是某正交投影变换(在某基下)的矩阵,故常称为正交投影矩阵.

*** 谱分解的几何意义

    - 如果二阶实正规矩阵 $A$ 有两个相同的特征值 $\lambda$ ,则 $A=\lambda{I}$ 就是它的谱分解.如果 $A$ 有两个不同的
      特征值 $\lambda_1$ 与 $\lambda_2$ ,则其谱分解为 $A=\lambda_1P_1+\lambda_2P_2$ .因此,对任意 $\alpha\in{R^2}$ ,
      有
      
      $A\alpha=\lambda_1P_1\alpha+\lambda_2P_2\alpha$
      
      计算内积可得 $(P_1\alpha,P_2\alpha)=(P_1\alpha)^TP_2\alpha=\alpha^TP_1^TP_2\alpha=0$ ,
      所以 $\lambda_1P_1\alpha$ 与 $\lambda_2P_2\alpha$ 是正交的向量,所以公式将 $A\alpha$ 分解成了两个正交向量的和.

    - 因此,二维正规矩阵的谱分解实际上是平面的正交投影变换的推广.

*** 利用谱分解求Hermite矩阵的逆
    - 如果 $A$ 是可逆 Hermite 矩阵,则可以利用 $A$ 的谱分解来求其逆矩阵.设 $A$ 的谱分解为
      
      $A=\sum_{i=1}^n\lambda_i\alpha_i\alpha_i^*$
      
      则
      
      $A^{-1}=\sum_{i=1}^{n}\frac{1}{\lambda_i}\alpha_i\alpha_i^{*}$

*** 单纯矩阵
    - 定义[p129]
      $n$ 阶可对角化矩阵 $A$ 称为单纯矩阵.可以类似于正规矩阵定义 $A$ 的谱分解.
      
*** 谱分解定理
    - 定理[p131]
      设 $A$ 为一个 $n$ 阶可对角化矩阵, $A$ 的谱为 $\sigma(A)=\{\lambda_1,\lambda_2,\cdots,\lambda_s\}$ ,其中 $\lambda_i$ 的重数为 $k_i$ .
      则存在唯一一组 $s$ 个 $n$ 阶方阵 $P_1,P_2,\cdots,P_s$ ,满足
      
      $(1)\ A=\sum_{i=1}^s\lambda_iP_i;\ (2)\ P_i^2=P_i;\ (3)\ P_iP_j=0(i\ne{}j)$
      
      $(4)\ \sum_{i=1}^sP_i=I;\ (5)\ r(P_i)=k_i$
      
      这些矩阵 $P_i$ 称为 矩阵 $A$ 的成分矩阵或主幂等矩阵.

    - 注意:与正规矩阵相比,一般矩阵的谱分解中的成分矩阵不一定是 Hermite 矩阵.因此,

      $Ax=\lambda_1P_1x+\lambda_2P_2x+\cdots+\lambda_sP_sx$ 中的诸向量 $P_ix$ 未必是正交的.

    - 推论[p132]
      设 $A=\sum_{i=1}^{s}\lambda_iP_i$ 是单纯矩阵 $A$ 的谱分解,则
      
      $A^m=\sum_{i=1}^s\lambda_i^mP_i$
      
      从而对任意多项式 $f(x)$ ,有 $f(A)=\sum_{i=1}^sf(\lambda_i)P_i$ .

** 矩阵的三角分解与Cholesky分解

*** 定义
    - 定义[p133]
      设 $A$ 是 $n$ 阶矩阵,如果存在上三角矩阵 $U$ 与单位下三角矩阵 $L$ 使得
      
      $A=LU$
      
      则称 $A$ 有三角分解或 $LU$ 分解,

*** LU分解的唯一性
    - 三角分解未必存在
      
    - 设 $A$ 是 $n$ 阶可逆矩阵,并且 $A$ 有三角分解 $A=LU$ ,则该分解是唯一的,
      且 $\mid{A}\mid=\mid{U}\mid=u_{11}u_{22}\cdots{u_{nn}}$ .

*** Cholesky分解
    - 定理[p133]
      实正定矩阵 $A$ 必有三角分解 $A=LU$ ,且存在唯一的对角元素均为正的下三角矩阵 $G$ ,使得 
      $A=GG^T$ (此称为Cholesky分解).矩阵 $G$ 称为Cholesky三角.

    - 定理[p135]
      设 $n$ 阶矩阵 $A$ 可逆,则 $A$ 存在三角分解 $\Longleftrightarrow{A}$ 的所有顺序主子式均非0.此时,唯一的存在
      一对单位下三角矩阵 $L^{'}$ 和单位上三角矩阵 $U^{'}$ 与对角矩阵 $D$ ,使得 $A=L^{'}DU^{'}$ ,其中 
      $D$ 与 $A$ 具有完全相同的顺序主子式.

    - 推论[p135]
      设 $n$ 阶矩阵 $A$ 的前 $r(A)$ 个顺序主子式均非0,则 $A$ 存在三角分解.

** 矩阵的 QR 分解

*** 定义
    - 即使可逆矩阵也可能不存在三角分解.矩阵的正交三角分解即是一种对任何可逆矩阵均存在的理想分解,
      其原理是Gram-Schmidt的正交化方法.

    - 定理[p136] 矩阵的正交三角分解

      设 $A\in{C^{n\times{n}}}$ ,且 $A$ 为满秩的,则存在唯一的酉矩阵 $U$ 和对角线元素都大于零(保证唯一性)的
      上三角矩阵 $R$ ,满足

      $A=UR$

    - 当 $A$ 为实满秩矩阵时,上面定理中的 $U$ 为正交矩阵,记为 $Q$ ,而 $R$ 为实上三角矩阵,因此 $UR$ 分解
      也称为 $QR$ 分解.

    - 推论[p137]
      设可逆矩阵 $A$ 的正交三角分解为 $A=UR$ ,则上三角矩阵 $R$ 的行列式的模等于矩阵 $A$ 的行列式的模.

*** 所有列满秩的矩阵均存在类似的正交三角分解

**** 矩阵的薄QR分解
     
    - 定理[p137]
      设 $A\in{C^{n\times{r}}}$ ,且 $A$ 是列满秩的,则
      
      $A=UR$
      
      其中, $U\in{C^{n\times{r}}}$ 的 $r$ 个列向量构成一组标准正交向量组, $R\in{C^{r\times{r}}}$ 为对角线元素大于零
      的上三角矩阵.此分解是唯一的.

**** 正交三角分解

     - 定理[[矩阵的薄QR分解]]可以作如下变化,即将 $U$ 取为 $n$ 阶酉矩阵,而将 $R$ 取为 $n\times{r}$ 阶准上三角矩阵,
       即
       
       \begin{equation}R=
       \begin{bmatrix}R_1\\0\end{bmatrix}
       \end{equation}
       
       其中 $r$ 阶上三角矩阵 $R_1$ 具有正对角元素.通常称此种分解为矩阵 $A$ 的正交三角分解.

     - 设列满秩矩阵 $A\in{C^{m\times{n}}}$ 的正交三角分解为 $A=UR$ ,则 $A^*A=R^*R$ .因此下三角矩阵
       $R^*$ 恰好是正定矩阵 $A^*A$ 的 Cholesky 三角.

** 矩阵的奇异值分解与极分解

*** 奇异值分解定理
****    定理[p139]
       设 $A=(a_{ij})\in{C^{m\times{n}}}(m\ge{n})$ ,且 $\sigma_1\ge{\sigma_2}\ge{\cdots}\ge{\sigma_r}>0$ ,
       则存在 $m$ 阶和 $n$ 阶的酉矩阵 $U$ 和 $V$ ,使得
      
       $A=UDV^*$
      
       其中 $D=diag(\sigma_1,\sigma_2,\cdots,\sigma_r,0,\cdots,0)_{m\times{n}}$ .
      
       上式称为矩阵 $A$ 的奇异值分解,简称为 SVD ,而 $\sigma_1,\cdots,\sigma_r,0,\cdots,0$ (共 $n$ 个)称为 $A$ 的奇异值.

****    由奇异值分解定理的证明可知
      
       \begin{eqnarray}
       Av_i=
       \begin{cases}
       \sigma_iu_i,\ 1\le{i}\le{r}\\
       0,\ r+1\le{i}\le{n}
       \end{cases}
       \end{eqnarray}
       与
      
       \begin{eqnarray}
       u_i^*A=
       \begin{cases}
       \sigma_iv_i^*,\ 1\le{i}\le{r}\\
       0,\ r+1\le{i}\le{m}
       \end{cases}
       \end{eqnarray}
      
       因此,矩阵 $V$ 与 $U$ 的列向量分别称为矩阵 $A$ 的右奇异向量和左奇异向量,而 $V$ 与 $U$ 分别
       称为 $A$ 的右奇异向量矩阵和左奇异向量矩阵.

****    推论[p141]
	- 设 $A$ 是正规矩阵,则可以由 $A$ 的谱分解导出 $A$ 的一个奇异值分解.设 $A=U^*\Lambda{U}$ ,其中
	  $\Lambda=diag(\lambda_1,\lambda_2,\cdots,\lambda_n)$ .则存在对角酉矩阵 $W$ ,使得
	  
	  $D=\Lambda{W^*}=diag(\mid{\lambda_1}\mid,\cdots,\mid{\lambda_n\mid})$
	  
	  于是得 $A=U^*\Lambda{W^*}WU=U^*DWU=U^*DV$ ,其中

	  矩阵 $V=WU$ 是酉矩阵,即 $A$ 的一个奇异值分解为 $A=U^*DV$ .

*** 奇异值分解的几何意义[p141]
    - 将 $A_{m\times{n}}=UDV^*$ 看作是从 $C^n$ 到 $C^m$ 的线性变换,则该线性变换首先在 $C^n$ 内
      将向量 $x$ 作一旋转而得到向量 $V^*x$ ,然后再将 $C^n$ 中的向量 $V^*x$ 沿前 $r=r(A)$ 个坐标
      作伸缩(其余坐标变为0)而得到 $C^m$ 中的向量 $DV^*x$ ,最后再在 $C^m$ 内作一旋转而得到
      向量 $UDV^*x$ .比较正规矩阵的酉对角化可知,此处的两次旋转可能不是互逆的.

*** 并向量分解,截尾奇异值分解
    - 将 $A$ 的奇异值分解展开可得
      
      $A=\sum_{i=1}^n\sigma_iu_iv_i^*$
      
      上式称为矩阵 $A$ 的并向量分解或奇异值分解展开.由于 $\sigma_i=0,i>r$ ,所以上式可写为
      
      $A=\sum_{i=1}^{r}\sigma_iu_iv^*_i=U_rD_rV^*_r$
      
      其中 $U_r,V_r$ 分别是 $U,V$ 的前 $r$ 列构成的矩阵,而 $D_r=diag(\sigma_1,\cdots,\sigma_r)$ .
      上式称为矩阵 $A$ 的截尾奇异值分解或薄奇异值分解.

**** $A$ 与 $A^*$ 具有相同的奇异值

     - 推论[p142]
       设 $A=(a_{ij})_{m\times{n}}$ 的秩为 $r$ ,则 $AA^*$ 与 $A^*A$ 有完全相同的非零特征值
       (相同的按重数计算) $\sigma^2_1,\sigma^2_2,\cdots,\sigma^2_r$ ,其中 $\sigma_1,\sigma_2,\cdots,\sigma_r$ 是 $A$
       的非零奇异值.因此, $A$ 与 $A^*$ 具有相同的奇异值.

**** $A$ 的逆矩阵的奇异值分解
     - 例[p142]
       设可逆矩阵 $A$ 的奇异值分解为 $A=UDV^*$ ,则其逆的奇异值分解为 $A^{-1}=VD^{-1}U^*$ .
       因此,若 $A$ 的奇异值为 $\sigma_1\ge{\sigma_2\ge{\cdots}},\ge\sigma_n>0$ ,则 $A^{-1}$ 的奇异值为
       $\frac{1}{\sigma_n}\ge{}\frac{1}{\sigma_{n-1}}\ge\cdots\ge{}\frac{1}{\sigma_1}>0$ .

     - 矩阵计算中的重要概念,矩阵 $A$ 的(谱)条件数,记为 $Cond(A)$ ,可以表示为
       
       $Cond(A)=\frac{\sigma_1(A)}{\sigma_n(A)}$

***  极分解
      - 定理[p142]
	设 $A\in{C^{n\times{n}}}$ ,则存在酉矩阵 $U$ 和唯一的半正定矩阵 $P$ ,使得
	
	$A=PU$
	
	上式称为矩阵 $A$ 的极分解.矩阵 $P$ 与 $U$ 分别称为 $A$ 的 Hermite 因子与酉因子.

      - 设 $A=U_1DV^*$ 是 $A$ 的奇异值分解,令 $P=U_1DU_1^*,U=U_1V^*$ ,
	即可得到矩阵的极分解.
	
*** 极分解的几何意义[p142]
    - 矩阵的极分解的几何意义是:先旋转,然后再沿着一组正交的方向作伸缩.

*** 利用矩阵的极分解判断正规性
    - 命题[p142]
      设 $A=PU$ 是矩阵 $A$ 的极分解,则
      
      $A$ 是正规矩阵$\Longleftrightarrow{}PU=UP$

*** 奇异值分解的性质
**** 正规矩阵的奇异值分解[p142]
   - 正规矩阵的奇异值是其特征值的模.特别地,半正定矩阵的特征值与奇异值相同.
**** 奇异值分解与矩阵的四个子空间[p142]
     - 设 $A=UDV^*$ 是 $m\times{n}$ 矩阵 $A$ 的一个奇异值分解, $r=r(A)$ ,则
       1) 酉矩阵 $U$ 的前 $r$ 列是 $A$ 的列空间的一组标准正交基
       2) 酉矩阵 $V$ 的前 $r$ 列是 $A^*$ 的列空间的一组标准正交基
       3) $U$ 的后 $m-r$ 列是 $A^*$ 的零空间的一组标准正交基
       4) $V$ 的后 $n-r$ 列是 $A$ 的零空间的一组标准正交基

**** 奇异值与特征值[p142]
     - 设 $\lambda$ 是 $n$ 阶矩阵 $A$ 的一个特征值,则 $\sigma_{max}(A)\ge{\mid{}\lambda\mid}\ge{}\sigma_{min}(A)$ .
       换言之,矩阵的最大奇异值与最小奇异值是其特征值的模的上下界.
     
**** 奇异值与矩阵的迹[p143]
     - 设 $A\in{C^{m\times{n}}}$ ,则 $tr(A^*A)=\sum_{i=1}^{r}\sigma_i^2$ .

**** 奇异值与奇异矩阵[p143]
     - 矩阵 $A$ 列满秩 $\Longleftrightarrow{A}$ 的奇异值均非 $0$ .特别地,
       方阵 $A$ 非奇异(列满秩) $\Longleftrightarrow{A}$ 的奇异值均非 $0$ .

     - 矩阵的奇异值较之其特征值的优点:
       1) 非零奇异值的个数恰好是该矩阵的秩

       2) 矩阵的非零特征值的个数一般比其秩小

       3) 常利用此点来计算矩阵的秩

     

     

