<2016-09-17 Sat>
* 配置你的github
#+BEGIN_SRC sh
git config --global user.name "Your name"
git config --global user.email "Your email"
#+END_SRC

* 创建公钥
** 生成两个 SSH key
   - 使用多个github账号
     #+BEGIN_SRC sh
     ssh-keygen -t rsa -C "your email address"
     #+END_SRC
     不要一路回车, 在第一个对话的时候输入重命名, 这会在目录～/.ssh/下创建相应的密钥文件

** 把 key 加到 ssh agent 上
   - 由于不是使用默认的 .ssh/id_rsa, 需要显示告诉 ssh agent 新的 key 的位置
     ssh-add ~/.ssh/id_rsa_work
   - 可以通过 ssh-add -l 来确认结果
     
** 上传密钥
   - 把 .ssh/id_rsa_work.pub 添加到work账号上
     - 在github.com的界面中添加 SSH Public Keys
       key的内容拷贝自~/.ssh/id_rsa_work.pub中的内容

** 配置 .ssh/config
   - touch .ssh/config
     #+BEGIN_EXAMPLE
     # pengzhou93
     Host pengzhou93
     HostName github.com
     PreferredAuthentications publickey
     IdentityFile /home/shhs/.ssh/id_rsa_pengzhou93
     User pengzhou93

     # zhoupengML
     Host zhoupengML
     HostName github.com
     PreferredAuthentications publickey
     IdentityFile /home/shhs/.ssh/id_rsa
     User zhoupengML
     #+END_EXAMPLE

** 连接测试
   - 链接成功,github上的key变成绿色
     #+BEGIN_SRC sh
     ssh -v git@github.com
     ssh -v git@pengzhou93
     #+END_SRC
     看到下面的信息表示验证成功
     Exit status 1

   - 如果遇到权限问题
     * cd .ssh
     * chmod 600 *

** Clone 到本地
   - 原来的写法
     git clone git@github.com:pengzhou93/repository.git
   - 现在的写法
     git clone git@pengzhou93:pengzhou93/repository.git
     git clone git@zhoupengML:zhoupengML/repository.git
     
** Push 到github上去
   git remote add origin git@pengzhou93:pengzhou93/repository.git
   git push origin master
   
* git使用
#+BEGIN_SRC sh
git init
git add .
git commit -m "message" file
#+END_SRC
** 设置默认编辑器
   git config --global core.editor "emacs"

** 两台主机之间交换代码
#+BEGIN_EXAMPLE
cd /codes/project

# 创建git代码仓库
git init
git add .
git commit -m "create project"

# 切换到project父目录，创建一个project-bare目录
cd ..
mkdir project-bare
cd project-bare

# 从原始代码仓库创建bare仓库，作为“中央”仓库，其他机器(包括本机的原始仓库)往这里push，从这里pull
git clone --bare ../project ./project-bare.git

# 回到project仓库目录
cd ../project

# 把project-bare添加为remote，
git remote add origin ../project-bare/project-bare.git
git branch --set-upstream-to=origin/master master

主机B
git clone <username>@<ip>:<port>:/codes/project-bare/project-bare.git ./project

#+END_EXAMPLE
** git submodule
   - Config file
     - .gitmodules

   - Add submodule
     - git submodule add url

   - 用来初始化本地配置文件
     - git submodule init

   - 从该项目中抓取所有数据并检出父项目中列出的合适的提交
     - git submodule update

   - Download contents of submodules
     - git submodule update --init --recursive

   - 想要在子模块 DbConnector 跟踪仓库的 “dev” 分支，
     那么可以在 .gitmodules 文件中设置（这样其他人也可以跟踪它）
     - git config -f .gitmodules submodule.DbConnector.branch dev
     - git submodule update --remote 
     - git submodule update --remote --rebase
     - git submodule update --remote --merge

   - 让 Git 在推送到主项目前检查所有子模块是否已推送
     - git push --recurse-submodules=check
     - git push --recurse-submodules=on-demand
       
   - 显示子模块的更改摘要
     - git config status.submodulesummary 1
       
** git branch
   - 显示本地分支和远程分支的对应关系
     - git branch -vv
     - git branch -a
     - git branch -r

   - 创建本地分支并与远程分支对应
     - git checkout -b gh-pages origin/gh-pages

   - 重命名分支名字
     - git branch -m oldbranchname newbranchname

   - 删除分支
     - git branch -d branch

   - 设置本地分支和远程分支的对应关系
     - git branch --set-upstream-to origin/dev

   - 切换分支
     - git checkout branch-name

** git push
   - 删除远程分支
     - git push origin :remote-branch

   - 将本地分支推送到远程分支
     - git push origin local_branch:remote_branch

** git merge
   - 合并分支
     - git merge merged-branch
     - git merge --abort
   - 冲突解决
     1) shows all files which require conflict resolution.
	git diff --name-status --diff-filter=U

     2) Open each of those files one by one, or all at once by:
	emacs $(git diff --name-only --diff-filter=U)

     3) When visiting a buffer requiring edits in Emacs, type
	ALT+x vc-resolve-conflicts

     4) This will open three buffers (mine, theirs, and the output buffer). 
	Navigate by pressing 'n' (next region), 'p' (prevision region). 
	Press 'a' and 'b' to copy mine or theirs region to the output buffer, respectively. 
	And/or edit the output buffer directly.

     5) When finished: Press 'q'. Emacs asks you if you want to save this buffer: yes. 
	After finishing a buffer mark it as resolved by running from the teriminal:
	git add FILENAME

     6) When finished with all buffers type
	git commit

** git fetch
   - 获取远程分支
     git fetch origin master
     git checkout -b master origin/master
   - one step
     git fetch origin remotebranch:localbranch

** git remote
   - Set remote url
     - git remote set-url origin url
       
** git rm
   - Delete dir
     - git rm -r directory
       git commit -m ""
     
** Roll back
   #+BEGIN_SRC sh
   git reflog : look up records of commit
   git reset --hard 33(id) : roll back to one version
   #+END_SRC

** 从其他分支提取文件
   #+BEGIN_EXAMPLE
   git checkout [branch] -- [file name]
   #+END_EXAMPLE
** 在github上创建一个repository并复制URL
#+BEGIN_SRC sh
git remote add origin git@github.com:zhoupengML/repository.git
#+END_SRC
** 提交代码
#+BEGIN_SRC sh
git push origin [local branch]
#+END_SRC
** Reset add
   #+BEGIN_EXAMPLE
   git reset file
   #+END_EXAMPLE
** Fetch remote refs
   #+BEGIN_EXAMPLE
   git pull origin branchname
   #+END_EXAMPLE
** 显示远程分支,Create branch
   #+BEGIN_SRC sh
   git branch -r 
   git branch --set-upstream-to origin/dev
   git checkout -b gh-pages origin/gh-pages
   git branch branch-name
   #+END_SRC
** Switch branch
   #+BEGIN_SRC sh
   git checkout branch-name
   #+END_SRC
** Delete remote branch
   #+BEGIN_SRC sh
   git push origin :remote-branch
   #+END_SRC
   咚！服务器上的分支没了。你最好特别留心这一页，因为你一定会用到那个命令，而且你很可能会忘掉它的
语法。有种方便记忆这条命令的方法：记住我们不久前见过的 git push [远程名] [本地分支]:[远程分支] 语法，如
果省略 [本地分支]，那就等于是在说“在这里提取空白然后把它变成[远程分支]”。

* Github Pages
** Create project pages
   #+BEGIN_EXAMPLE
    $ git clone https://github.com/USERNAME/PROJECT.git PROJECT
    $ git checkout --orphan gh-pages # Create unparented branch
    $ git rm -rf .  # Remove untracked file in current branch
    $ git add .
    $ git commit -a -m "First pages commit"
    $ git push origin gh-pages
   #+END_EXAMPLE

* reference
  - [[http://blog.csdn.net/small_rice_/article/details/45095323]]
  - [[http://yuyang0.github.io/notes/git.html]]
  - [[http://yuyang0.github.io/]]
