#+OPTIONS: tex:t
#+TITLE: 最优化
#+AUTHOR: Peng Zhou


* Chapter 1 凸集与凸函数

** 凸函数的判别

   - 设$f:R^n\to{R}$ , 且二阶连续可微， 则下列命题等价

     1) $f$ 是凸函数

     2) 对 $\forall{x, y} \in{R^n}$ , 有 $f(y)\ge{f(x)+\nabla{f(x)^T}(y-x)}$

     3) 梯度函数 $\nabla{f(x)}$ 单调

	$$[\nabla{f(y)}-\nabla{f(x)}]^T(y-x)\ge{0}$$

     4) $\forall{x}\in{R^n} , Hesse$ 矩阵 $\nabla^2{f(x)}$ 半正定 (正定矩阵: positive definite matrix)

*** 正定二次型的定义 [[http://wenku.baidu.com/link?url=J912nnUKjFJYkRt-w89TPkotscm0SnFl4XwYXHSrxOEDau0TLibvB9J3K81hKOyH-B3K3JWS2_hE9lW6eFj7S1GhD8wDhOg7nqpU2QQ7oLO][ref]]

    * 定义
      在实二次型 $f(x_1,x_2,...,x_n)$ 中, 若对于任意一组不全为 $0$ 的实数 $c_1,c_2,...,c_n$ ,
      都有 $f(x_1,x_2,...,x_n)>0$ , 则称该二次型为正定的; 
      若 $f(x_1,x_2,...,x_n)\ge{0}$ , 则称 $f$ 为半正定二次型; 
      若 $f(x_1,x_2,...,x_n)<0$ , 则称 $f$ 为负定二次型; 
      若 $f(x_1,x_2,...,x_n)\le{0}$ , 则称 $f$ 为半负定二次型;
      若实二次型既不是半正定又不是半负定的则称为不定二次型.
      
*** 正定矩阵的定义 [[http://wenku.baidu.com/link?url=J912nnUKjFJYkRt-w89TPkotscm0SnFl4XwYXHSrxOEDau0TLibvB9J3K81hKOyH-B3K3JWS2_hE9lW6eFj7S1GhD8wDhOg7nqpU2QQ7oLO][ref]]

    * 定义
      若实二次型 $f(x_1,x_2,...,x_n)=X^TAX$ 正定, 则称实对称矩阵 $A$ 正定;
      若实二次型 $f(x_1,x_2,...,x_n)=X^TAX$ 半正定, 则称实对称矩阵 $A$ 半正定;
      若实二次型 $f(x_1,x_2,...,x_n)=X^TAX$ 负定, 则称实对称矩阵 $A$ 负定;
      若实二次型 $f(x_1,x_2,...,x_n)=X^TAX$ 半负定, 则称实对称矩阵 $A$ 半负定;
      若实二次型 $f(x_1,x_2,...,x_n)=X^TAX$ 不定, 则称实对称矩阵 $A$ 不定.

*** 正定矩阵的判定

**** 正定矩阵判定定理

     1. $n$ 元实二次型 $f(x_1,x_2,...,x_n)=X^TAX$ 是正定的充要条件是:
	它的标准型的系数全为正.
	
	+ 用合同变换法化二次型为标准型 [[http://wenku.baidu.com/link?url=1M3RiheBvR4d7sHe1S4htMZzH902EgWo0APzOax7F5oREnwilnTwWQI-F0Els_uinKhevcOL9lPRQnM6-PFL34kUTC96jdC4bwwQRsMDsNS][ref]]

	  1) 写出二次型的矩阵 $A$

	  2) 作 $(A\ E)\xrightarrow[elementary\ row\ operation\ of\ E]{congruent\ transformation\ of\ A}(\land{\ P^T})$ , 求出 $P^T$

	  3) 作非退化的线性变换 $X=PY$ , 将二次型化为标准型
      
*** 矩阵的等价, 相似, 合同 [[http://wenku.baidu.com/link?url=QRehRaAsSmbyVxbYFkyJQRkXw5y-KmKN0eSoFwW7sU--566tbOd3m5NEtCHw8s6LEN4Y_RGH3nMugFTvABikDMFrcjf3ZbOQMVBNR9ZrFI_][ref]]

**** 矩阵等价的定义

     如果矩阵 $A$ 可以经过一系列初等变换变成 $B$ , 则 $A$ 与 $B$ 等价,
     记为 $A\cong{B}$ .

**** 矩阵相似的定义
     
     设 $A,B$ 是数域 $F$ 上的 $n$ 阶方阵, 如果存在数域 $F$ 上的 $n$ 阶
     可逆矩阵 $P$ , 使得 $B=P^{-1}AP$ , 则称 $A$ 与 $B$ 相似,
     记为 $A\sim{B}$ .

**** 矩阵合同的定义
     
     设 $A,B$ 是数域 $F$ 上的 $n$ 阶方阵, 如果存在数域 $F$ 上的 $n$ 阶
     可逆矩阵 $P$ , 使得 $P^{T}AP=B$ , 则称在数域 $F$ 上 $A$ 与 $B$ 合同.


*  Chapter 2 线性规划的基本性质

** 线性规划标准形式
   \begin{eqnarray}
    \min{}&\ &\sum_{j=1}^{n}{c_jx_j}\\
    s.t.\ \ \sum_{j=1}^{n}\alpha_{ij}x_j&=&b_i, i=1,...,m\nonumber\\
    x_j&\ge&{0}, j=1,...,n\nonumber
   \end{eqnarray}

矩阵形式:

   \begin{eqnarray}
    \label{eq:2}
    \min&{c^Tx}&\\
    s.t.\ \ Ax&=&b\nonumber\\
    x&\ge&{0}\nonumber
   \end{eqnarray}

**  可行域
    1. 在线性规划中,约束条件均为线性等式及不等式,满足这些条件的点的集合是凸集
    2. 线性规划的可行域是凸集

** 最优极点							    :Theorem:
   1.线性规划如果存在最优解,那么最优值一定能在某极点上达到

   2.设可行域的极点为 $x^{(1)},x^{(2)},...,x^{(k)}$, 极方向为 $d^{(1)},d^{(2)},...,d^{(l)}$, 根据定理[p12],
      任何可行点 $x$ 可以表示为

      \begin{eqnarray}
      x=\sum_{j=1}^k\lambda_jx^{(j)}&+&\sum_{j=1}^l\mu_jd^{(j)}\\
      \sum_{j=1}^k\lambda_j&=&1\nonumber\\
      \lambda_j&\ge&{0},\ j=1,...,k\nonumber\\
      \mu_j&\ge&0,\ j=1,...,l
      \end{eqnarray}

   - 定理2.2.2 设线性规划的可行域非空,则
     1) 线性规划存在有限最优解的充要条件是所有 $c^Td^{(j)}$  为非负数.
     2) 若线性规划存在有限最优解,则目标函数的最优值可在某个极点上达到.

**  最优基本可行解						    :Theorem:
    1. 对于线性规划,基本可行解与可行域的极点之间总存在着对应关系.
       
    2. 定理2.2.3 
       令 $K=\{x|Ax=b,x\ge{0}\},A$ 是 $m\times{n}$ 矩阵, $A$  的秩为 $m$, 则 $K$
        的极点集与 $Ax=b,x\ge{0}$ 的基本可行解集等价.

    3.  线性规划问题的求解,可归结为求最优基本可行解.

** 基本可行解的存在问题						    :Theorem:
   1. 定理1.4.1 [p12]
       若多面集 $S=\{x|Ax=b,x\ge{0}\}$ 非空,则存在有限个极点(有限个基本可行解).
   2. 定理2.2.4 [p34]
      如果 $Ax=b,x\ge{0}$  有可行解,则一定存在基本可行解.其中 $A$ 是 $m\times{n}$ 矩阵,
      $A$ 的秩为 $m$.

** Practice								:Def:
   1. 定义2.2.1 基本解 [p30]
      
      \begin{equation}
      x=\begin{bmatrix}x_B\\x_N\end{bmatrix}
      =\begin{bmatrix}B^{-1}b\\0\end{bmatrix}
      \end{equation}
      
       称为方程组 $Ax=b$  的一个基本解. 矩阵 $A$ 的秩为 $m$, $A=[B,N]$, $B$  是 $m$ 阶
       可逆矩阵.
